### ISSUE TITLE
Maintain scroll position on returning from image screen

### ISSUE THREAD

**Issue by devashishmamgain** [MobiComKit/mobi-com-kit#45]
Most likely it is happening because of loading the conversation again inside onResume.
This is done so that we can reload any new incoming message.
One way to avoid is to maintain the flag whether any new message is arrived for the current conversation or not, if yes then do the reload otherwise don't.

**Comment by adarshmishra** [comment]
Changes done:
last conversation time is stored and onResume will query DB based on lastConversationTime.

@devashishmamgain please test and close.

**Comment by devashishmamgain** [comment]
@adarshmishra take a picture, it is showing retry, click on retry, app crashed, happening every time, not sure if it related to this issue or not, not able to get logs through my mobile.

**Comment by devashishmamgain** [comment]
will file picture upload as separate bug
