### ISSUE TITLE
 requestLayout() improperly called by android.widget.ProgressBar

### ISSUE THREAD

**Issue by devashishmamgain** [MobiComKit/mobi-com-kit#46]
Following keeps coming in logs:
06-23 19:24:22.623    2340-2340/com.mobicomkit.sample I/Choreographer﹕ Skipped 104 frames!  The application may be doing too much work on its main thread.
06-23 19:24:22.815    2340-2340/com.mobicomkit.sample W/View﹕ requestLayout() improperly called by android.widget.ProgressBar{3661bcdf V.ED.... ......ID 420,0-564,144 #7f0a008e app:id/spinner} during layout: running second layout pass
06-23 19:24:24.704

**Comment by devashishmamgain** [comment]
Still coming, open sample app, click on "Chat" then the following is coming in logs:

06-30 20:50:35.237    1886-1931/com.mobicomkit.sample W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa5420f00, error=EGL_SUCCESS
06-30 20:50:35.495    1886-1886/com.mobicomkit.sample I/MTBroadcastReceiver﹕ Received broadcast, action: INSTRUCTION, message: null
06-30 20:50:35.650    1886-2241/com.mobicomkit.sample I/MobiComConversation﹕ loading conversation with  lastConversationloadTime null
06-30 20:50:35.739    1886-1886/com.mobicomkit.sample W/View﹕ requestLayout() improperly called by android.widget.ProgressBar{3cc8cd65 V.ED.... ......ID 420,0-564,144 #7f0a008e app:id/spinner} during layout: running second layout pass
06-30 20:50:36.441    1886-2241/com.mobicomkit.sample I/Conversation﹕ Received response from server: {"message":[]}

**Comment by adarshmishra** [comment]
@devashishmamgain ,
Assigning  for testing.

**Comment by devashishmamgain** [comment]
@adarshmishra tested, working fine.
